// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nadgwtgvzcbybcswdfqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hZGd3dGd2emNieWJjc3dkZnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTAxNzEsImV4cCI6MjA2NTI4NjE3MX0.2l2fXcr0OY8te0-95VYx_40yPqfkYq-INl8KHWDJbnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);